name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Retrieve required files
      run: wget https://archive.org/download/nointro.n64/Super%20Mario%2064%20%28Japan%29.7z/Super%20Mario%2064%20%28Japan%29.z64 && mv "Super Mario 64 (Japan).z64" baserom.jp.z64
      
    - name: Compile
      run: make -j32 VERSION=jp
    - name: Publish Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: linuxBuild
        path: 'build/jp/sm64.jp.z64'
